export const ALL_CHAINS = [
  { id: 1, name: "Ethereum", rpc: "https://eth.drpc.org", stablecoins: ["USDC","USDT","DAI"] },
  { id: 137, name: "Polygon", rpc: "https://polygon-rpc.com", stablecoins: ["USDC","USDT"] },
  { id: 42161, name: "Arbitrum", rpc: "https://arb1.arbitrum.io/rpc", stablecoins: ["USDC","USDT"] },
  { id: 10, name: "Optimism", rpc: "https://mainnet.optimism.io", stablecoins: ["USDC","USDT"] },
  { id: 8453, name: "Base", rpc: "https://mainnet.base.org", stablecoins: ["USDC"] },
  { id: 56, name: "BNB Chain", rpc: "https://bsc-dataseed1.binance.org", stablecoins: ["USDC","USDT"] },
  { id: 43114, name: "Avalanche", rpc: "https://api.avax.network/ext/bc/C/rpc", stablecoins: ["USDC","USDT"] },
  { id: 250, name: "Fantom", rpc: "https://fantom.drpc.org", stablecoins: ["USDC","USDT"] },
  { id: 100, name: "Gnosis", rpc: "https://rpc.gnosischain.com", stablecoins: ["USDC","xDAI"] },
  { id: 42220, name: "Celo", rpc: "https://forno.celo.org", stablecoins: ["cUSD","USDC"] },
  { id: 324, name: "zkSync Era", rpc: "https://mainnet.era.zksync.io", stablecoins: ["USDC"] },
  { id: 59144, name: "Linea", rpc: "https://rpc.linea.build", stablecoins: ["USDC"] },
  { id: 534352, name: "Scroll", rpc: "https://rpc.scroll.io", stablecoins: ["USDC"] },
  { id: 5000, name: "Mantle", rpc: "https://rpc.mantle.xyz", stablecoins: ["USDC"] },
  { id: 1284, name: "Moonbeam", rpc: "https://rpc.api.moonbeam.network", stablecoins: ["USDC"] },
  { id: 1101, name: "Polygon zkEVM", rpc: "https://zkevm-rpc.com", stablecoins: ["USDC"] },
  { id: 81457, name: "Blast", rpc: "https://rpc.blast.io", stablecoins: ["USDC"] },
  { id: 7777777, name: "Zora", rpc: "https://rpc.zora.energy", stablecoins: [] },
  { id: 34443, name: "Mode", rpc: "https://mainnet.mode.network", stablecoins: [] },
  { id: 480, name: "World Chain", rpc: "https://worldchain-mainnet.g.alchemy.com/public", stablecoins: [] },
];
export const CHAIN_COUNT = ALL_CHAINS.length;
