import { createFileRoute, Link } from "@tanstack/react-router";
import { useState, useEffect, useCallback } from "react";
import {
  fetchDailySignal,
  fetchSignalHistory,
  hasUnlockedPremiumClient,
  STRIPE_PREMIUM_PRICE_ID,
  seedDemoSignals,
} from "~/lib/trading-signals";
import type { TradingSignal, SignalStats } from "~/lib/trading-signals";

export const Route = createFileRoute("/signals")({
  component: SignalsPage,
  head: () => ({
    meta: [
      { title: "HSMC — Trading Signals" },
      {
        name: "description",
        content:
          "AI-powered trading signals. Get daily crypto trading signals generated by 29 AI agents analyzing real-time market data.",
      },
    ],
  }),
});

// ── Helpers ─────────────────────────────────────────────────────────

function getStatusEmoji(status: TradingSignal["status"]): string {
  switch (status) {
    case "hit":
      return "✅";
    case "miss":
      return "❌";
    case "expired":
      return "⏸️";
    default:
      return "🔄";
  }
}

function getDirectionEmoji(direction: "LONG" | "SHORT"): string {
  return direction === "LONG" ? "🟢" : "🔴";
}

function formatPrice(p: number): string {
  if (p >= 1000) return `$${p.toLocaleString("en-US")}`;
  if (p >= 1) return `$${p.toFixed(2)}`;
  return `$${p.toFixed(4)}`;
}

function formatPct(v: number): string {
  const sign = v >= 0 ? "+" : "";
  return `${sign}${v.toFixed(1)}%`;
}

function timeAgo(ts: number): string {
  const diff = Date.now() - ts;
  const mins = Math.floor(diff / 60000);
  if (mins < 1) return "just now";
  if (mins < 60) return `${mins}m ago`;
  const hours = Math.floor(mins / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  return `${days}d ago`;
}

// ── Stripe Checkout ─────────────────────────────────────────────────

function getStripeCheckoutUrl(): string {
  const origin =
    typeof window !== "undefined" ? window.location.origin : "https://hsmc.io";
  return `https://buy.stripe.com/14k5oGe0egmA9mE3cd?client_reference_id=${encodeURIComponent(origin)}/signals?session_id={CHECKOUT_SESSION_ID}`;
}

// ── Page Component ──────────────────────────────────────────────────

function SignalsPage() {
  const [signal, setSignal] = useState<TradingSignal | null>(null);
  const [history, setHistory] = useState<TradingSignal[]>([]);
  const [stats, setStats] = useState<SignalStats | null>(null);
  const [loading, setLoading] = useState(true);
  const [unlocked, setUnlocked] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  // Check URL params for Stripe redirect
  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const sessionId = params.get("session_id");
    if (sessionId) {
      setUnlocked(true);
      hasUnlockedPremiumClient(sessionId);
      // Clean URL
      window.history.replaceState({}, "", "/signals");
    } else {
      setUnlocked(hasUnlockedPremiumClient());
    }
  }, []);

  // Fetch signals
  useEffect(() => {
    async function load() {
      try {
        setLoading(true);
        // Seed demo data if needed (for first-time visitors)
        seedDemoSignals();

        const [dailyResult, historyResult] = await Promise.all([
          fetchDailySignal(),
          fetchSignalHistory(),
        ]);

        if (dailyResult) {
          setSignal(dailyResult);
        } else {
          setError("Unable to generate signal — market data may be unavailable.");
        }

        if (historyResult) {
          setHistory(historyResult.history);
          setStats(historyResult.stats);
        }
      } catch (err) {
        console.error("[Signals] load failed:", err);
        setError("Failed to load signals. Please try again.");
      } finally {
        setLoading(false);
      }
    }
    load();
  }, []);

  const handleUnlock = useCallback(() => {
    window.location.href = getStripeCheckoutUrl();
  }, []);

  const handleCopy = useCallback(() => {
    if (!signal) return;
    const text = [
      `📊 HSMC Signal: ${signal.pair} — ${signal.direction}`,
      `Entry: ${formatPrice(signal.entryPrice)}`,
      `Stop Loss: ${formatPrice(signal.stopLoss)}`,
      `Take Profit: ${formatPrice(signal.takeProfit)}`,
      `Confidence: ${signal.confidence}%`,
      ``,
      `Analysis: ${signal.reasoning}`,
      `Generated: ${new Date(signal.timestamp).toISOString()}`,
      `Powered by HSMC AI Trading Platform`,
    ].join("\n");
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }, [signal]);

  // ── Render ──────────────────────────────────────────────────────
  return (
    <div className="min-h-dvh pt-20 pb-16 px-4 sm:px-6">
      <div className="mx-auto max-w-3xl">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-3xl sm:text-4xl font-black font-mono tracking-tight text-[#e0e6ed] mb-2">
            <span className="text-[#00e676]">{">"}</span> TRADING_SIGNALS
          </h1>
          <p className="text-sm text-[#546e7a] font-mono">
            AI-powered market analysis from 29 autonomous agents
          </p>
        </div>

        {/* Stats Bar */}
        {stats && stats.totalSignals > 0 && (
          <div className="glass-card p-4 mb-6 flex flex-wrap items-center gap-4 sm:gap-8">
            <StatItem
              label="Win Rate"
              value={`${stats.winRate.toFixed(0)}%`}
              color={stats.winRate >= 50 ? "text-[#00e676]" : "text-[#ff5252]"}
            />
            <StatItem
              label="Total Signals"
              value={String(stats.totalSignals)}
              color="text-[#e0e6ed]"
            />
            <StatItem
              label="Hit"
              value={String(stats.hitCount)}
              color="text-[#00e676]"
            />
            <StatItem
              label="Miss"
              value={String(stats.missCount)}
              color="text-[#ff5252]"
            />
          </div>
        )}

        {/* Loading State */}
        {loading && (
          <div className="glass-card p-12 text-center">
            <div className="inline-block w-8 h-8 border-2 border-[#00e676] border-t-transparent rounded-full animate-spin mb-4" />
            <p className="text-[#546e7a] font-mono text-sm">
              Analyzing markets...
            </p>
          </div>
        )}

        {/* Error State */}
        {!loading && error && (
          <div className="glass-card p-8 text-center border-red-500/30">
            <p className="text-[#ff5252] font-mono text-sm">{error}</p>
            <button
              onClick={() => window.location.reload()}
              className="mt-4 px-4 py-2 rounded-lg border border-[#1a1f2e] bg-[#0d1117] text-[#00e676] font-mono text-xs hover:bg-[#141b24] transition-colors"
            >
              RETRY
            </button>
          </div>
        )}

        {/* Premium Signal Card */}
        {!loading && signal && (
          <div className="mb-8">
            {!unlocked ? (
              /* ── Locked View ── */
              <div className="glass-card p-6 sm:p-8 relative overflow-hidden">
                {/* Lock indicator */}
                <div className="absolute top-4 right-4 flex items-center gap-1.5 px-3 py-1 rounded-full border border-yellow-500/30 bg-yellow-500/10">
                  <span className="text-yellow-400 text-xs">🔒</span>
                  <span className="text-yellow-400 text-[0.65rem] font-mono font-bold tracking-wider">
                    PREMIUM
                  </span>
                </div>

                <div className="mb-4">
                  <span className="text-[0.65rem] font-mono font-bold text-[#546e7a] tracking-wider">
                    DAILY SIGNAL — FREE PREVIEW
                  </span>
                </div>

                {/* Free preview: pair + direction */}
                <div className="flex items-center gap-3 mb-5">
                  <span className="text-2xl font-black text-[#e0e6ed] font-mono">
                    {signal.pair}
                  </span>
                  <span
                    className={`px-3 py-0.5 rounded text-xs font-bold font-mono ${
                      signal.direction === "LONG"
                        ? "bg-green-500/15 text-green-400 border border-green-500/30"
                        : "bg-red-500/15 text-red-400 border border-red-500/30"
                    }`}
                  >
                    {getDirectionEmoji(signal.direction)} {signal.direction}
                  </span>
                </div>

                {/* Blurred analysis preview */}
                <div className="mb-6 p-4 rounded-lg bg-[#0d1117]/80 border border-[#1a1f2e] relative">
                  <p className="text-[#78909c] text-sm font-mono leading-relaxed line-clamp-2">
                    {signal.reasoning.split("\n")[0]}
                  </p>
                  <div className="absolute inset-0 bg-gradient-to-b from-transparent via-[#080a0f]/40 to-[#080a0f]/80 rounded-lg pointer-events-none" />
                </div>

                {/* Unlock button */}
                <button
                  onClick={handleUnlock}
                  className="w-full py-3.5 rounded-xl bg-gradient-to-r from-[#00e676] to-[#00bcd4] text-[#080a0f] font-bold font-mono text-sm tracking-wider hover:opacity-90 transition-opacity shadow-lg shadow-[#00e676]/20"
                >
                  UNLOCK FULL SIGNAL — 25 RON
                </button>

                <p className="mt-3 text-center text-[0.6rem] text-[#546e7a] font-mono">
                  One-time payment. Secure checkout via Stripe.
                </p>

                {/* Already unlocked link */}
                <div className="mt-4 pt-4 border-t border-[#1a1f2e] text-center">
                  <p className="text-[0.65rem] text-[#546e7a] font-mono">
                    Already unlocked?{" "}
                    <span
                      className="text-[#00e676] cursor-pointer hover:underline"
                      onClick={() => setUnlocked(true)}
                    >
                      View signal →
                    </span>
                  </p>
                </div>
              </div>
            ) : (
              /* ── Unlocked View ── */
              <div className="glass-card p-6 sm:p-8 relative border-[#00e676]/20 blue-glow">
                {/* Unlocked indicator */}
                <div className="absolute top-4 right-4 flex items-center gap-1.5 px-3 py-1 rounded-full border border-green-500/30 bg-green-500/10">
                  <span className="text-green-400 text-xs">🔓</span>
                  <span className="text-green-400 text-[0.65rem] font-mono font-bold tracking-wider">
                    UNLOCKED
                  </span>
                </div>

                <div className="mb-4">
                  <span className="text-[0.65rem] font-mono font-bold text-[#546e7a] tracking-wider">
                    PREMIUM SIGNAL
                  </span>
                </div>

                {/* Pair + Direction */}
                <div className="flex items-center gap-3 mb-6">
                  <span className="text-2xl font-black text-[#e0e6ed] font-mono">
                    {signal.pair}
                  </span>
                  <span
                    className={`px-3 py-0.5 rounded text-xs font-bold font-mono ${
                      signal.direction === "LONG"
                        ? "bg-green-500/15 text-green-400 border border-green-500/30"
                        : "bg-red-500/15 text-red-400 border border-red-500/30"
                    }`}
                  >
                    {getDirectionEmoji(signal.direction)} {signal.direction}
                  </span>
                </div>

                {/* Key metrics */}
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-6">
                  <SignalMetric
                    label="Entry"
                    value={formatPrice(signal.entryPrice)}
                  />
                  <SignalMetric
                    label="Stop Loss"
                    value={formatPrice(signal.stopLoss)}
                    color="text-[#ff5252]"
                  />
                  <SignalMetric
                    label="Take Profit"
                    value={formatPrice(signal.takeProfit)}
                    color="text-[#00e676]"
                  />
                  <SignalMetric
                    label="Confidence"
                    value={`${signal.confidence}%`}
                    color={
                      signal.confidence >= 70
                        ? "text-[#00e676]"
                        : signal.confidence >= 50
                          ? "text-[#ffd700]"
                          : "text-[#ff5252]"
                    }
                  />
                </div>

                {/* Analysis */}
                <div className="p-4 rounded-lg bg-[#0d1117]/80 border border-[#1a1f2e] mb-6">
                  <h3 className="text-[0.65rem] font-mono font-bold text-[#546e7a] tracking-wider mb-3">
                    AI ANALYSIS
                  </h3>
                  <p className="text-[#b0bec5] text-sm font-mono leading-relaxed whitespace-pre-line">
                    {signal.reasoning}
                  </p>
                </div>

                {/* Meta */}
                <div className="flex items-center justify-between mb-6 text-[0.65rem] font-mono text-[#546e7a]">
                  <span>
                    Generated {timeAgo(signal.timestamp)} • Signal ID:{" "}
                    {signal.id.slice(-8)}
                  </span>
                </div>

                {/* Actions */}
                <div className="flex gap-3">
                  <button
                    onClick={handleCopy}
                    className="flex-1 py-2.5 rounded-lg border border-[#1a1f2e] bg-[#0d1117] text-[#00e676] font-mono text-xs font-bold hover:bg-[#141b24] transition-colors"
                  >
                    {copied ? "COPIED ✓" : "COPY TO CLIPBOARD"}
                  </button>
                  <button
                    onClick={() => {
                      const url = window.location.href;
                      navigator.clipboard.writeText(url);
                    }}
                    className="py-2.5 px-4 rounded-lg border border-[#1a1f2e] bg-[#0d1117] text-[#b0bec5] font-mono text-xs hover:bg-[#141b24] transition-colors"
                  >
                    SHARE
                  </button>
                </div>
              </div>
            )}
          </div>
        )}

        {/* Signal History */}
        <div className="mb-16">
          <h2 className="text-lg font-bold text-[#e0e6ed] font-mono mb-4 flex items-center gap-2">
            <span className="text-[#00e676]">{">"}</span>
            SIGNAL_HISTORY
          </h2>

          {history.length === 0 ? (
            <div className="glass-card p-8 text-center">
              <p className="text-[#546e7a] font-mono text-sm">
                No signal history yet.
              </p>
            </div>
          ) : (
            <div className="glass-card overflow-hidden">
              {/* Table Header */}
              <div className="grid grid-cols-12 gap-2 px-4 py-3 border-b border-[#1a1f2e] bg-[#0d1117]/50">
                <span className="col-span-1 text-[0.6rem] font-mono font-bold text-[#546e7a] tracking-wider uppercase">
                  Status
                </span>
                <span className="col-span-3 text-[0.6rem] font-mono font-bold text-[#546e7a] tracking-wider uppercase">
                  Pair
                </span>
                <span className="col-span-2 text-[0.6rem] font-mono font-bold text-[#546e7a] tracking-wider uppercase">
                  Direction
                </span>
                <span className="col-span-2 text-[0.6rem] font-mono font-bold text-[#546e7a] tracking-wider uppercase">
                  Confidence
                </span>
                <span className="col-span-2 text-[0.6rem] font-mono font-bold text-[#546e7a] tracking-wider uppercase">
                  Entry
                </span>
                <span className="col-span-2 text-[0.6rem] font-mono font-bold text-[#546e7a] tracking-wider uppercase text-right">
                  When
                </span>
              </div>

              {/* Table Rows */}
              <div className="divide-y divide-[#1a1f2e]">
                {history.map((s) => (
                  <div
                    key={s.id}
                    className="grid grid-cols-12 gap-2 px-4 py-2.5 hover:bg-[#0d1117]/40 transition-colors items-center"
                  >
                    <span className="col-span-1 text-sm">
                      {getStatusEmoji(s.status)}
                    </span>
                    <span className="col-span-3 text-xs font-mono font-bold text-[#e0e6ed]">
                      {s.pair}
                    </span>
                    <span className="col-span-2">
                      <span
                        className={`text-[0.65rem] font-mono font-bold ${
                          s.direction === "LONG"
                            ? "text-green-400"
                            : "text-red-400"
                        }`}
                      >
                        {s.direction}
                      </span>
                    </span>
                    <span className="col-span-2">
                      <span className="text-[0.65rem] font-mono text-[#b0bec5]">
                        {s.confidence}%
                      </span>
                    </span>
                    <span className="col-span-2">
                      <span className="text-[0.65rem] font-mono text-[#78909c]">
                        {formatPrice(s.entryPrice)}
                      </span>
                    </span>
                    <span className="col-span-2 text-right">
                      <span className="text-[0.6rem] font-mono text-[#546e7a]">
                        {timeAgo(s.timestamp)}
                      </span>
                    </span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Footer CTA */}
        {!unlocked && !loading && (
          <div className="text-center mb-16">
            <div className="glass-card p-8 max-w-md mx-auto">
              <h3 className="text-lg font-bold text-[#e0e6ed] font-mono mb-2">
                Ready to trade smarter?
              </h3>
              <p className="text-sm text-[#78909c] font-mono mb-6">
                Get one premium AI signal daily. Our 29-agent consensus
                consistently outperforms manual trading.
              </p>
              <button
                onClick={handleUnlock}
                className="w-full py-3 rounded-xl bg-gradient-to-r from-[#00e676] to-[#00bcd4] text-[#080a0f] font-bold font-mono text-sm tracking-wider hover:opacity-90 transition-opacity shadow-lg shadow-[#00e676]/20"
              >
                UNLOCK PREMIUM SIGNAL — 25 RON
              </button>
              <p className="mt-3 text-[0.6rem] text-[#546e7a] font-mono">
                Powered by Stripe • Secure payment • Instant access
              </p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

// ── Sub-Components ──────────────────────────────────────────────────

function StatItem({
  label,
  value,
  color,
}: {
  label: string;
  value: string;
  color: string;
}) {
  return (
    <div className="flex items-center gap-2">
      <span className="text-[0.6rem] font-mono font-bold text-[#546e7a] tracking-wider uppercase">
        {label}
      </span>
      <span className={`text-sm font-mono font-bold ${color}`}>{value}</span>
    </div>
  );
}

function SignalMetric({
  label,
  value,
  color = "text-[#e0e6ed]",
}: {
  label: string;
  value: string;
  color?: string;
}) {
  return (
    <div className="p-3 rounded-lg bg-[#0d1117]/60 border border-[#1a1f2e] text-center">
      <div className="text-[0.6rem] font-mono font-bold text-[#546e7a] tracking-wider mb-1">
        {label}
      </div>
      <div className={`text-sm font-mono font-bold ${color}`}>{value}</div>
    </div>
  );
}
