/**
 * PaymentSettlement Contract Deployment Script
 *
 * Usage:
 *   npx hardhat run src/contracts/deploy.ts --network polygonAmoy
 *   npx hardhat run src/contracts/deploy.ts --network polygon
 *
 * Environment variables:
 *   PRIVATE_KEY — deployer private key (without 0x prefix)
 *   POLYGON_AMOY_RPC_URL — Amoy testnet RPC URL
 *   POLYGON_RPC_URL — Polygon mainnet RPC URL
 */

import { createPublicClient, createWalletClient, http, type Address } from "viem";
import { polygon, polygonAmoy } from "viem/chains";
import { privateKeyToAccount } from "viem/accounts";

// ── Contract Bytecode & ABI ──────────────────────────────────────────
// Generated by compiling PaymentSettlement.sol with solc
// In production, these would be loaded from artifacts
const CONTRACT_BYTECODE = "0x" as const; // Replace with compiled bytecode
const CONTRACT_ABI = [] as const; // Replace with compiled ABI

// ── Configuration ────────────────────────────────────────────────────

interface DeployConfig {
  chain: typeof polygon | typeof polygonAmoy;
  rpcUrl: string;
  chainName: string;
}

async function getConfig(): Promise<DeployConfig> {
  const network = process.env.DEPLOY_NETWORK || "amoy";

  if (network === "mainnet" || network === "polygon") {
    const rpcUrl = process.env.POLYGON_RPC_URL;
    if (!rpcUrl) {
      throw new Error("POLYGON_RPC_URL environment variable is required for mainnet deployment");
    }
    return { chain: polygon, rpcUrl, chainName: "Polygon Mainnet" };
  }

  // Default: Amoy testnet
  const rpcUrl = process.env.POLYGON_AMOY_RPC_URL || "https://polygon-amoy.g.alchemy.com/v2/demo";
  return { chain: polygonAmoy, rpcUrl, chainName: "Polygon Amoy (Testnet)" };
}

// ── Deploy ───────────────────────────────────────────────────────────

async function main() {
  console.log("═══ PaymentSettlement Contract Deployer ═══\n");

  const privateKey = process.env.PRIVATE_KEY;
  if (!privateKey) {
    console.error("❌ PRIVATE_KEY environment variable is required.");
    console.error("   Set it in .env or export PRIVATE_KEY=your_key_here");
    process.exit(1);
  }

  const config = await getConfig();
  console.log(`📡 Network: ${config.chainName}`);
  console.log(`🔗 RPC:     ${config.rpcUrl}\n`);

  const account = privateKeyToAccount(privateKey as `0x${string}`);

  const publicClient = createPublicClient({
    chain: config.chain,
    transport: http(config.rpcUrl),
  });

  const walletClient = createWalletClient({
    chain: config.chain,
    transport: http(config.rpcUrl),
    account,
  });

  console.log(`👛 Deployer: ${account.address}`);

  const balance = await publicClient.getBalance({ address: account.address });
  console.log(`💰 Balance:  ${balance} wei\n`);

  if (balance === 0n) {
    console.error("❌ Deployer has no funds. Get testnet MATIC from a faucet.");
    process.exit(1);
  }

  console.log("🚀 Deploying PaymentSettlement...\n");

  try {
    const txHash = await walletClient.deployContract({
      abi: CONTRACT_ABI,
      bytecode: CONTRACT_BYTECODE,
      account,
    });

    console.log(`📝 TX Hash: ${txHash}`);

    const receipt = await publicClient.waitForTransactionReceipt({ hash: txHash });
    const contractAddress = receipt.contractAddress;

    if (!contractAddress) {
      console.error("❌ Deployment failed — no contract address in receipt.");
      process.exit(1);
    }

    console.log("\n✅ PaymentSettlement deployed successfully!");
    console.log(`📍 Address:  ${contractAddress}`);
    console.log(`🔗 Explorer: ${config.chain.blockExplorers?.default.url}/address/${contractAddress}`);
    console.log(`⛽ Gas used: ${receipt.gasUsed}`);
    console.log(`📦 Block:    ${receipt.blockNumber}\n`);

    // Verify token configuration
    console.log("📋 Accepted tokens:");
    console.log("   USDC:  0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359 (mainnet)");
    console.log("   USDC:  0x41E94Eb019C0762f9Bfcf9Fb1E58725BfB0e7582 (amoy)");
    console.log("   USDT:  0xc2132D05D31c914a87C6611C10748AEb04B58e8F (mainnet)");
    console.log("   MATIC: native\n");

    console.log("📌 Add to your .env file:");
    console.log(`   VITE_POS_CONTRACT_ADDRESS=${contractAddress}\n`);

  } catch (err) {
    console.error("❌ Deployment failed:", err);
    process.exit(1);
  }
}

// Only run when executed directly
if (import.meta.main || require.main === module) {
  main().catch((err) => {
    console.error("Fatal:", err);
    process.exit(1);
  });
}

export { main };
