/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as SwapRouteImport } from './routes/swap'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as EarnRouteImport } from './routes/earn'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as ChainsRouteImport } from './routes/chains'
import { Route as ArbitrageRouteImport } from './routes/arbitrage'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChainsChainIdRouteImport } from './routes/chains.$chainId'

const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const SwapRoute = SwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const EarnRoute = EarnRouteImport.update({
  id: '/earn',
  path: '/earn',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const ChainsRoute = ChainsRouteImport.update({
  id: '/chains',
  path: '/chains',
  getParentRoute: () => rootRouteImport,
} as any)
const ArbitrageRoute = ArbitrageRouteImport.update({
  id: '/arbitrage',
  path: '/arbitrage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChainsChainIdRoute = ChainsChainIdRouteImport.update({
  id: '/$chainId',
  path: '/$chainId',
  getParentRoute: () => ChainsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arbitrage': typeof ArbitrageRoute
  '/chains': typeof ChainsRouteWithChildren
  '/contracts': typeof ContractsRoute
  '/earn': typeof EarnRoute
  '/portfolio': typeof PortfolioRoute
  '/swap': typeof SwapRoute
  '/withdraw': typeof WithdrawRoute
  '/chains/$chainId': typeof ChainsChainIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arbitrage': typeof ArbitrageRoute
  '/chains': typeof ChainsRouteWithChildren
  '/contracts': typeof ContractsRoute
  '/earn': typeof EarnRoute
  '/portfolio': typeof PortfolioRoute
  '/swap': typeof SwapRoute
  '/withdraw': typeof WithdrawRoute
  '/chains/$chainId': typeof ChainsChainIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arbitrage': typeof ArbitrageRoute
  '/chains': typeof ChainsRouteWithChildren
  '/contracts': typeof ContractsRoute
  '/earn': typeof EarnRoute
  '/portfolio': typeof PortfolioRoute
  '/swap': typeof SwapRoute
  '/withdraw': typeof WithdrawRoute
  '/chains/$chainId': typeof ChainsChainIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arbitrage'
    | '/chains'
    | '/contracts'
    | '/earn'
    | '/portfolio'
    | '/swap'
    | '/withdraw'
    | '/chains/$chainId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arbitrage'
    | '/chains'
    | '/contracts'
    | '/earn'
    | '/portfolio'
    | '/swap'
    | '/withdraw'
    | '/chains/$chainId'
  id:
    | '__root__'
    | '/'
    | '/arbitrage'
    | '/chains'
    | '/contracts'
    | '/earn'
    | '/portfolio'
    | '/swap'
    | '/withdraw'
    | '/chains/$chainId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArbitrageRoute: typeof ArbitrageRoute
  ChainsRoute: typeof ChainsRouteWithChildren
  ContractsRoute: typeof ContractsRoute
  EarnRoute: typeof EarnRoute
  PortfolioRoute: typeof PortfolioRoute
  SwapRoute: typeof SwapRoute
  WithdrawRoute: typeof WithdrawRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swap': {
      id: '/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earn': {
      id: '/earn'
      path: '/earn'
      fullPath: '/earn'
      preLoaderRoute: typeof EarnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chains': {
      id: '/chains'
      path: '/chains'
      fullPath: '/chains'
      preLoaderRoute: typeof ChainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arbitrage': {
      id: '/arbitrage'
      path: '/arbitrage'
      fullPath: '/arbitrage'
      preLoaderRoute: typeof ArbitrageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chains/$chainId': {
      id: '/chains/$chainId'
      path: '/$chainId'
      fullPath: '/chains/$chainId'
      preLoaderRoute: typeof ChainsChainIdRouteImport
      parentRoute: typeof ChainsRoute
    }
  }
}

interface ChainsRouteChildren {
  ChainsChainIdRoute: typeof ChainsChainIdRoute
}

const ChainsRouteChildren: ChainsRouteChildren = {
  ChainsChainIdRoute: ChainsChainIdRoute,
}

const ChainsRouteWithChildren =
  ChainsRoute._addFileChildren(ChainsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArbitrageRoute: ArbitrageRoute,
  ChainsRoute: ChainsRouteWithChildren,
  ContractsRoute: ContractsRoute,
  EarnRoute: EarnRoute,
  PortfolioRoute: PortfolioRoute,
  SwapRoute: SwapRoute,
  WithdrawRoute: WithdrawRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
