/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as SwapRouteImport } from './routes/swap'
import { Route as StakeRouteImport } from './routes/stake'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as GasRouteImport } from './routes/gas'
import { Route as EarnRouteImport } from './routes/earn'
import { Route as DepositRouteImport } from './routes/deposit'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ChainsRouteImport } from './routes/chains'
import { Route as BacktestingRouteImport } from './routes/backtesting'
import { Route as ArbitrageRouteImport } from './routes/arbitrage'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChainsXrpRouteImport } from './routes/chains.xrp'
import { Route as ChainsTronRouteImport } from './routes/chains.tron'
import { Route as ChainsSolanaRouteImport } from './routes/chains.solana'
import { Route as ChainsChainIdRouteImport } from './routes/chains.$chainId'

const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const SwapRoute = SwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const StakeRoute = StakeRouteImport.update({
  id: '/stake',
  path: '/stake',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const GasRoute = GasRouteImport.update({
  id: '/gas',
  path: '/gas',
  getParentRoute: () => rootRouteImport,
} as any)
const EarnRoute = EarnRouteImport.update({
  id: '/earn',
  path: '/earn',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositRoute = DepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChainsRoute = ChainsRouteImport.update({
  id: '/chains',
  path: '/chains',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestingRoute = BacktestingRouteImport.update({
  id: '/backtesting',
  path: '/backtesting',
  getParentRoute: () => rootRouteImport,
} as any)
const ArbitrageRoute = ArbitrageRouteImport.update({
  id: '/arbitrage',
  path: '/arbitrage',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChainsXrpRoute = ChainsXrpRouteImport.update({
  id: '/xrp',
  path: '/xrp',
  getParentRoute: () => ChainsRoute,
} as any)
const ChainsTronRoute = ChainsTronRouteImport.update({
  id: '/tron',
  path: '/tron',
  getParentRoute: () => ChainsRoute,
} as any)
const ChainsSolanaRoute = ChainsSolanaRouteImport.update({
  id: '/solana',
  path: '/solana',
  getParentRoute: () => ChainsRoute,
} as any)
const ChainsChainIdRoute = ChainsChainIdRouteImport.update({
  id: '/$chainId',
  path: '/$chainId',
  getParentRoute: () => ChainsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/arbitrage': typeof ArbitrageRoute
  '/backtesting': typeof BacktestingRoute
  '/chains': typeof ChainsRouteWithChildren
  '/chat': typeof ChatRoute
  '/contracts': typeof ContractsRoute
  '/dashboard': typeof DashboardRoute
  '/deposit': typeof DepositRoute
  '/earn': typeof EarnRoute
  '/gas': typeof GasRoute
  '/network': typeof NetworkRoute
  '/portfolio': typeof PortfolioRoute
  '/risk': typeof RiskRoute
  '/settings': typeof SettingsRoute
  '/stake': typeof StakeRoute
  '/swap': typeof SwapRoute
  '/trade': typeof TradeRoute
  '/training': typeof TrainingRoute
  '/vault': typeof VaultRoute
  '/withdraw': typeof WithdrawRoute
  '/chains/$chainId': typeof ChainsChainIdRoute
  '/chains/solana': typeof ChainsSolanaRoute
  '/chains/tron': typeof ChainsTronRoute
  '/chains/xrp': typeof ChainsXrpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/arbitrage': typeof ArbitrageRoute
  '/backtesting': typeof BacktestingRoute
  '/chains': typeof ChainsRouteWithChildren
  '/chat': typeof ChatRoute
  '/contracts': typeof ContractsRoute
  '/dashboard': typeof DashboardRoute
  '/deposit': typeof DepositRoute
  '/earn': typeof EarnRoute
  '/gas': typeof GasRoute
  '/network': typeof NetworkRoute
  '/portfolio': typeof PortfolioRoute
  '/risk': typeof RiskRoute
  '/settings': typeof SettingsRoute
  '/stake': typeof StakeRoute
  '/swap': typeof SwapRoute
  '/trade': typeof TradeRoute
  '/training': typeof TrainingRoute
  '/vault': typeof VaultRoute
  '/withdraw': typeof WithdrawRoute
  '/chains/$chainId': typeof ChainsChainIdRoute
  '/chains/solana': typeof ChainsSolanaRoute
  '/chains/tron': typeof ChainsTronRoute
  '/chains/xrp': typeof ChainsXrpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/arbitrage': typeof ArbitrageRoute
  '/backtesting': typeof BacktestingRoute
  '/chains': typeof ChainsRouteWithChildren
  '/chat': typeof ChatRoute
  '/contracts': typeof ContractsRoute
  '/dashboard': typeof DashboardRoute
  '/deposit': typeof DepositRoute
  '/earn': typeof EarnRoute
  '/gas': typeof GasRoute
  '/network': typeof NetworkRoute
  '/portfolio': typeof PortfolioRoute
  '/risk': typeof RiskRoute
  '/settings': typeof SettingsRoute
  '/stake': typeof StakeRoute
  '/swap': typeof SwapRoute
  '/trade': typeof TradeRoute
  '/training': typeof TrainingRoute
  '/vault': typeof VaultRoute
  '/withdraw': typeof WithdrawRoute
  '/chains/$chainId': typeof ChainsChainIdRoute
  '/chains/solana': typeof ChainsSolanaRoute
  '/chains/tron': typeof ChainsTronRoute
  '/chains/xrp': typeof ChainsXrpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/alerts'
    | '/analytics'
    | '/arbitrage'
    | '/backtesting'
    | '/chains'
    | '/chat'
    | '/contracts'
    | '/dashboard'
    | '/deposit'
    | '/earn'
    | '/gas'
    | '/network'
    | '/portfolio'
    | '/risk'
    | '/settings'
    | '/stake'
    | '/swap'
    | '/trade'
    | '/training'
    | '/vault'
    | '/withdraw'
    | '/chains/$chainId'
    | '/chains/solana'
    | '/chains/tron'
    | '/chains/xrp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/alerts'
    | '/analytics'
    | '/arbitrage'
    | '/backtesting'
    | '/chains'
    | '/chat'
    | '/contracts'
    | '/dashboard'
    | '/deposit'
    | '/earn'
    | '/gas'
    | '/network'
    | '/portfolio'
    | '/risk'
    | '/settings'
    | '/stake'
    | '/swap'
    | '/trade'
    | '/training'
    | '/vault'
    | '/withdraw'
    | '/chains/$chainId'
    | '/chains/solana'
    | '/chains/tron'
    | '/chains/xrp'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/alerts'
    | '/analytics'
    | '/arbitrage'
    | '/backtesting'
    | '/chains'
    | '/chat'
    | '/contracts'
    | '/dashboard'
    | '/deposit'
    | '/earn'
    | '/gas'
    | '/network'
    | '/portfolio'
    | '/risk'
    | '/settings'
    | '/stake'
    | '/swap'
    | '/trade'
    | '/training'
    | '/vault'
    | '/withdraw'
    | '/chains/$chainId'
    | '/chains/solana'
    | '/chains/tron'
    | '/chains/xrp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ArbitrageRoute: typeof ArbitrageRoute
  BacktestingRoute: typeof BacktestingRoute
  ChainsRoute: typeof ChainsRouteWithChildren
  ChatRoute: typeof ChatRoute
  ContractsRoute: typeof ContractsRoute
  DashboardRoute: typeof DashboardRoute
  DepositRoute: typeof DepositRoute
  EarnRoute: typeof EarnRoute
  GasRoute: typeof GasRoute
  NetworkRoute: typeof NetworkRoute
  PortfolioRoute: typeof PortfolioRoute
  RiskRoute: typeof RiskRoute
  SettingsRoute: typeof SettingsRoute
  StakeRoute: typeof StakeRoute
  SwapRoute: typeof SwapRoute
  TradeRoute: typeof TradeRoute
  TrainingRoute: typeof TrainingRoute
  VaultRoute: typeof VaultRoute
  WithdrawRoute: typeof WithdrawRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swap': {
      id: '/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stake': {
      id: '/stake'
      path: '/stake'
      fullPath: '/stake'
      preLoaderRoute: typeof StakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gas': {
      id: '/gas'
      path: '/gas'
      fullPath: '/gas'
      preLoaderRoute: typeof GasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earn': {
      id: '/earn'
      path: '/earn'
      fullPath: '/earn'
      preLoaderRoute: typeof EarnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit': {
      id: '/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof DepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chains': {
      id: '/chains'
      path: '/chains'
      fullPath: '/chains'
      preLoaderRoute: typeof ChainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtesting': {
      id: '/backtesting'
      path: '/backtesting'
      fullPath: '/backtesting'
      preLoaderRoute: typeof BacktestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arbitrage': {
      id: '/arbitrage'
      path: '/arbitrage'
      fullPath: '/arbitrage'
      preLoaderRoute: typeof ArbitrageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chains/xrp': {
      id: '/chains/xrp'
      path: '/xrp'
      fullPath: '/chains/xrp'
      preLoaderRoute: typeof ChainsXrpRouteImport
      parentRoute: typeof ChainsRoute
    }
    '/chains/tron': {
      id: '/chains/tron'
      path: '/tron'
      fullPath: '/chains/tron'
      preLoaderRoute: typeof ChainsTronRouteImport
      parentRoute: typeof ChainsRoute
    }
    '/chains/solana': {
      id: '/chains/solana'
      path: '/solana'
      fullPath: '/chains/solana'
      preLoaderRoute: typeof ChainsSolanaRouteImport
      parentRoute: typeof ChainsRoute
    }
    '/chains/$chainId': {
      id: '/chains/$chainId'
      path: '/$chainId'
      fullPath: '/chains/$chainId'
      preLoaderRoute: typeof ChainsChainIdRouteImport
      parentRoute: typeof ChainsRoute
    }
  }
}

interface ChainsRouteChildren {
  ChainsChainIdRoute: typeof ChainsChainIdRoute
  ChainsSolanaRoute: typeof ChainsSolanaRoute
  ChainsTronRoute: typeof ChainsTronRoute
  ChainsXrpRoute: typeof ChainsXrpRoute
}

const ChainsRouteChildren: ChainsRouteChildren = {
  ChainsChainIdRoute: ChainsChainIdRoute,
  ChainsSolanaRoute: ChainsSolanaRoute,
  ChainsTronRoute: ChainsTronRoute,
  ChainsXrpRoute: ChainsXrpRoute,
}

const ChainsRouteWithChildren =
  ChainsRoute._addFileChildren(ChainsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  ArbitrageRoute: ArbitrageRoute,
  BacktestingRoute: BacktestingRoute,
  ChainsRoute: ChainsRouteWithChildren,
  ChatRoute: ChatRoute,
  ContractsRoute: ContractsRoute,
  DashboardRoute: DashboardRoute,
  DepositRoute: DepositRoute,
  EarnRoute: EarnRoute,
  GasRoute: GasRoute,
  NetworkRoute: NetworkRoute,
  PortfolioRoute: PortfolioRoute,
  RiskRoute: RiskRoute,
  SettingsRoute: SettingsRoute,
  StakeRoute: StakeRoute,
  SwapRoute: SwapRoute,
  TradeRoute: TradeRoute,
  TrainingRoute: TrainingRoute,
  VaultRoute: VaultRoute,
  WithdrawRoute: WithdrawRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
