/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as SwapRouteImport } from './routes/swap'
import { Route as StakeRouteImport } from './routes/stake'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as EarnRouteImport } from './routes/earn'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as ChainsRouteImport } from './routes/chains'
import { Route as ArbitrageRouteImport } from './routes/arbitrage'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChainsChainIdRouteImport } from './routes/chains.$chainId'
import { Route as ApiChatStreamRouteImport } from './routes/api/chat-stream'

const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const SwapRoute = SwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const StakeRoute = StakeRouteImport.update({
  id: '/stake',
  path: '/stake',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const EarnRoute = EarnRouteImport.update({
  id: '/earn',
  path: '/earn',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const ChainsRoute = ChainsRouteImport.update({
  id: '/chains',
  path: '/chains',
  getParentRoute: () => rootRouteImport,
} as any)
const ArbitrageRoute = ArbitrageRouteImport.update({
  id: '/arbitrage',
  path: '/arbitrage',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChainsChainIdRoute = ChainsChainIdRouteImport.update({
  id: '/$chainId',
  path: '/$chainId',
  getParentRoute: () => ChainsRoute,
} as any)
const ApiChatStreamRoute = ApiChatStreamRouteImport.update({
  id: '/api/chat-stream',
  path: '/api/chat-stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/arbitrage': typeof ArbitrageRoute
  '/chains': typeof ChainsRouteWithChildren
  '/contracts': typeof ContractsRoute
  '/earn': typeof EarnRoute
  '/portfolio': typeof PortfolioRoute
  '/settings': typeof SettingsRoute
  '/stake': typeof StakeRoute
  '/swap': typeof SwapRoute
  '/vault': typeof VaultRoute
  '/withdraw': typeof WithdrawRoute
  '/api/chat-stream': typeof ApiChatStreamRoute
  '/chains/$chainId': typeof ChainsChainIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/arbitrage': typeof ArbitrageRoute
  '/chains': typeof ChainsRouteWithChildren
  '/contracts': typeof ContractsRoute
  '/earn': typeof EarnRoute
  '/portfolio': typeof PortfolioRoute
  '/settings': typeof SettingsRoute
  '/stake': typeof StakeRoute
  '/swap': typeof SwapRoute
  '/vault': typeof VaultRoute
  '/withdraw': typeof WithdrawRoute
  '/api/chat-stream': typeof ApiChatStreamRoute
  '/chains/$chainId': typeof ChainsChainIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/arbitrage': typeof ArbitrageRoute
  '/chains': typeof ChainsRouteWithChildren
  '/contracts': typeof ContractsRoute
  '/earn': typeof EarnRoute
  '/portfolio': typeof PortfolioRoute
  '/settings': typeof SettingsRoute
  '/stake': typeof StakeRoute
  '/swap': typeof SwapRoute
  '/vault': typeof VaultRoute
  '/withdraw': typeof WithdrawRoute
  '/api/chat-stream': typeof ApiChatStreamRoute
  '/chains/$chainId': typeof ChainsChainIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/analytics'
    | '/arbitrage'
    | '/chains'
    | '/contracts'
    | '/earn'
    | '/portfolio'
    | '/settings'
    | '/stake'
    | '/swap'
    | '/vault'
    | '/withdraw'
    | '/api/chat-stream'
    | '/chains/$chainId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/analytics'
    | '/arbitrage'
    | '/chains'
    | '/contracts'
    | '/earn'
    | '/portfolio'
    | '/settings'
    | '/stake'
    | '/swap'
    | '/vault'
    | '/withdraw'
    | '/api/chat-stream'
    | '/chains/$chainId'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/analytics'
    | '/arbitrage'
    | '/chains'
    | '/contracts'
    | '/earn'
    | '/portfolio'
    | '/settings'
    | '/stake'
    | '/swap'
    | '/vault'
    | '/withdraw'
    | '/api/chat-stream'
    | '/chains/$chainId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ArbitrageRoute: typeof ArbitrageRoute
  ChainsRoute: typeof ChainsRouteWithChildren
  ContractsRoute: typeof ContractsRoute
  EarnRoute: typeof EarnRoute
  PortfolioRoute: typeof PortfolioRoute
  SettingsRoute: typeof SettingsRoute
  StakeRoute: typeof StakeRoute
  SwapRoute: typeof SwapRoute
  VaultRoute: typeof VaultRoute
  WithdrawRoute: typeof WithdrawRoute
  ApiChatStreamRoute: typeof ApiChatStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swap': {
      id: '/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stake': {
      id: '/stake'
      path: '/stake'
      fullPath: '/stake'
      preLoaderRoute: typeof StakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earn': {
      id: '/earn'
      path: '/earn'
      fullPath: '/earn'
      preLoaderRoute: typeof EarnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chains': {
      id: '/chains'
      path: '/chains'
      fullPath: '/chains'
      preLoaderRoute: typeof ChainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arbitrage': {
      id: '/arbitrage'
      path: '/arbitrage'
      fullPath: '/arbitrage'
      preLoaderRoute: typeof ArbitrageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chains/$chainId': {
      id: '/chains/$chainId'
      path: '/$chainId'
      fullPath: '/chains/$chainId'
      preLoaderRoute: typeof ChainsChainIdRouteImport
      parentRoute: typeof ChainsRoute
    }
    '/api/chat-stream': {
      id: '/api/chat-stream'
      path: '/api/chat-stream'
      fullPath: '/api/chat-stream'
      preLoaderRoute: typeof ApiChatStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChainsRouteChildren {
  ChainsChainIdRoute: typeof ChainsChainIdRoute
}

const ChainsRouteChildren: ChainsRouteChildren = {
  ChainsChainIdRoute: ChainsChainIdRoute,
}

const ChainsRouteWithChildren =
  ChainsRoute._addFileChildren(ChainsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  AnalyticsRoute: AnalyticsRoute,
  ArbitrageRoute: ArbitrageRoute,
  ChainsRoute: ChainsRouteWithChildren,
  ContractsRoute: ContractsRoute,
  EarnRoute: EarnRoute,
  PortfolioRoute: PortfolioRoute,
  SettingsRoute: SettingsRoute,
  StakeRoute: StakeRoute,
  SwapRoute: SwapRoute,
  VaultRoute: VaultRoute,
  WithdrawRoute: WithdrawRoute,
  ApiChatStreamRoute: ApiChatStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
